### ISSUE TITLE
How do you create solr collection?

### ISSUE THREAD

**Issue by tdhz77** [hwillson/meteor-solr-demo#13]
I've created the solrconfig.xml in var/solr/data/testcore/conf
I've imported the schema using the admin interface ->Core "testcore" -> Documents - > solr cmmand raw xml - > Submit document.

I get the following error.

```
3/23/2016, 10:26:50 AM
	
ERROR
	
null
	
SolrCore
	
org.apache.solr.common.SolrException: undefined field: "doctype"
3/23/2016, 10:26:50 AM
	
ERROR
	
null
	
SolrCore
	
org.apache.solr.common.SolrException: undefined field: "doctype"
3/23/2016, 10:26:51 AM
	
ERROR
	
null
	
SolrCore
	
org.apache.solr.common.SolrException: undefined field: "doctype"
3/23/2016, 10:28:21 AM
	
ERROR
	
null
	
ShowFileRequestHandler
	
Can not find: admin-extra.menu-top.html [/var/solr/data/testcore/conf/admin-extra.menu-top.html]
3/23/2016, 10:28:21 AM
	
ERROR
	
null
	
ShowFileRequestHandler
	
Can not find: admin-extra.menu-bottom.html [/var/solr/data/testcore/conf/admin-extra.menu-bottom.html]
3/23/2016, 10:28:21 AM
	
ERROR
	
null
	
ShowFileRequestHandler
	
Can not find: admin-extra.html [/var/solr/data/testcore/conf/admin-extra.html]

Meteor shows:

> 20160323-10:26:51.341(-5)? Request method: GET
> I20160323-10:26:51.341(-5)? Status code: 400 - Bad Request
> I20160323-10:26:51.341(-5)? Request headers: 
> I20160323-10:26:51.341(-5)? accept: application/json; charset=utf-8
> I20160323-10:26:51.341(-5)? host: localhost:8983
> I20160323-10:26:51.341(-5)? Response headers: 
> I20160323-10:26:51.342(-5)? cache-control: no-cache, no-store
> I20160323-10:26:51.342(-5)? pragma: no-cache
> I20160323-10:26:51.342(-5)? expires: Sat, 01 Jan 2000 01:00:00 GMT
> I20160323-10:26:51.342(-5)? last-modified: Wed, 23 Mar 2016 15:26:51 GMT
> I20160323-10:26:51.342(-5)? etag: "153a415e3ca"
> I20160323-10:26:51.342(-5)? content-type: text/plain; charset=UTF-8
> I20160323-10:26:51.342(-5)? transfer-encoding: chunked
> 
> ```

**Comment by hwillson** [comment]
Did you add the `schema.xml` file alongside the `solrconfig.xml` file? The `doctype` field is defined in the `schema.xml`.

**Comment by tdhz77** [comment]
TY, Ok imported the schema and added the schema.xml file to the dir. I get this error now, which I'm unsure.

` Exception while invoking method 'App.methods.autosuggest.getSuggestions' Error: failed [500] {"responseHeader":{"status":500,"QTime":4},"error":{"msg":"suggester was not built","trace":"java.lang.IllegalStateException: suggester was not built\n\tat org.apache.lucene.search.suggest.analyzing.AnalyzingInfixSuggester.lookup(AnalyzingInfixSuggester.java:533)\n\tat org.apache.lucene.search.suggest.analyzing.AnalyzingInfixSuggester.lookup(AnalyzingInfixSuggester.java:452)\n\tat org.apache.solr.spelling.suggest.fst.AnalyzingInfixLookupFactory$1.lookup(AnalyzingInfixLookupFactory.java:121)\n\ta...


`

**Comment by hwillson** [comment]
Ah yes, the Solr suggester can be a pain - the easiest way to work around this is to call `suggest.build=true` to build the suggestions. So something like:
http://localhost:8983/solr/testcore/suggesthandler1?suggest.q=something&suggest.build=true

**Comment by tdhz77** [comment]
Sorry @hwillson  I'm trying to understand this whole thing. How would I insert data into Solr, so that I can test out the search. All I get now is search not found (*).

**Comment by hwillson** [comment]
No problem at all - I just pushed a few test docs into the repo under `/private/solr/data`. Copy these files somewhere that your Solr install can see them, then run something like the following to add them into the collection:
```
post -c testcore /opt/solr_test_docs/*.xml
```

**Comment by tdhz77** [comment]
Thanks @hwilson got it going. Still getting error with autosuggestion. So, If I have a meteor collection of PDF's can I hook this up to work with the solr fairly easily you think?

**Comment by hwillson** [comment]
After you import your docs you'll likely need to regen the suggestions, using something like:

> http://localhost:8983/solr/testcore/suggesthandler1?suggest.q=something&suggest.build=true

Regrading the collection of PDFs, are they stored in Mongo? If so I'd recommend indexing them directly from Mongo itself, to get them into Solr. I've never tried indexing directly from Mongo, but this might help:

http://blog.mongodb.org/post/29127828146/introducing-mongo-connector
